name: Build Android APK

on:
  push:
    branches: [ main, master ] # Triggers when you push to main or master
  workflow_dispatch: # Gives you a manual button to click and compile anytime

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Change Gradle Script Permissions
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Output APK
      uses: actions/upload-artifact@v4
      with:
        name: App-Debug-APK
        path: app/build/outputs/apk/debug/*.apk
